<a href="https://colab.research.google.com/github/salmeronale/metodos-numericos/blob/main/eliminaci%C3%B3n_gaussiana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
#definir una función del proceso
def eliminacion_gaussiana(A, b):

    n = len(A)
    A = A.astype(float)
    b = b.astype(float)

    print("matriz inicial:")
    print(A)
    print("vector independiente inicial:")
    print(b)

    #recorrer las columnas
    for k in range(n - 1):
        #verificar si el pivote es 0 y realizar intercambio de filas si es necesario
        if A[k, k] == 0:
            for i in range(k + 1, n):
                if A[i, k] != 0:
                    A[[k, i]] = A[[i, k]]
                    b[[k, i]] = b[[i, k]]
                    print(f"\nintercambio de filas {k} y {i} por pivote 0:")
                    print(A)
                    print("vector independiente:")
                    print(b)
                    break
            else:
                raise ValueError("no se puede resolver: el sistema tiene un pivote 0 en la columna actual y no es posible intercambiar filas.")

        #eliminación gaussiana
        for i in range(k + 1, n):
            factor = A[i, k] / A[k, k]
            A[i, k:] -= factor * A[k, k:]
            b[i] -= factor * b[k]

        print(f"\nmatriz después de la eliminación en la columna {k+1}:")
        print(A)
        print("vector independiente:")
        print(b)

    #sustitución hacia atrás
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]

    print("\nmatriz triangular superior:")
    print(A)
    print("vector independiente final:")
    print(b)

    return x

In [6]:
#definir una función para solicitar los datos
def datos():

    n = int(input("ingrese el número de ecuaciones: "))
    m = n + 1

    print("ingrese los coeficientes de la matriz aumentada (separados por un espacio en blanco):")
    matriz_aumentada = []
    for i in range(n):
        fila = list(map(float, input(f"Fila {i + 1}: ").split()))
        if len(fila) != m:
            raise ValueError(f"cada fila debe tener exactamente {m} valores.")
        matriz_aumentada.append(fila)

    matriz_aumentada = np.array(matriz_aumentada)
    A = matriz_aumentada[:, :-1]
    b = matriz_aumentada[:, -1]

    return A, b


In [10]:
# ejecución de las funciones
try:
    A, b = datos()
    solucion = eliminacion_gaussiana(A, b)
    print("")
    print("la solución es:", solucion)
except Exception as e:
    print("Error:", e)



ingrese el número de ecuaciones: 4
ingrese los coeficientes de la matriz aumentada (separados por un espacio en blanco):
Fila 1: 1 -1 2 -1 -8
Fila 2: 2 -2 3 -3 -20
Fila 3: 1 1 1 0 -2
Fila 4: 1 -1 4 3 4
matriz inicial:
[[ 1. -1.  2. -1.]
 [ 2. -2.  3. -3.]
 [ 1.  1.  1.  0.]
 [ 1. -1.  4.  3.]]
vector independiente inicial:
[ -8. -20.  -2.   4.]

matriz después de la eliminación en la columna 1:
[[ 1. -1.  2. -1.]
 [ 0.  0. -1. -1.]
 [ 0.  2. -1.  1.]
 [ 0.  0.  2.  4.]]
vector independiente:
[-8. -4.  6. 12.]

intercambio de filas 1 y 2 por pivote 0:
[[ 1. -1.  2. -1.]
 [ 0.  2. -1.  1.]
 [ 0.  0. -1. -1.]
 [ 0.  0.  2.  4.]]
vector independiente:
[-8.  6. -4. 12.]

matriz después de la eliminación en la columna 2:
[[ 1. -1.  2. -1.]
 [ 0.  2. -1.  1.]
 [ 0.  0. -1. -1.]
 [ 0.  0.  2.  4.]]
vector independiente:
[-8.  6. -4. 12.]

matriz después de la eliminación en la columna 3:
[[ 1. -1.  2. -1.]
 [ 0.  2. -1.  1.]
 [ 0.  0. -1. -1.]
 [ 0.  0.  0.  2.]]
vector independiente:
[-8.  6.