<a href="https://colab.research.google.com/github/salmeronale/metodos-numericos/blob/main/Factorizaci%C3%B3nLU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
#definir una función que ejecute el algoritmo de factorización LU
def fLU(A):
    n = A.shape[0]  # Dimensión de la matriz

    # Inicializar matrices L y U
    L = np.eye(n)  # Diagonal de L como 1
    U = np.zeros((n, n))

    for i in range(n):
        # Paso 4: Calcular valores de la diagonal
        sum_diag = sum(L[i, k] * U[k, i] for k in range(i))
        U[i, i] = A[i, i] - sum_diag

        if U[i, i] == 0:
            print("Factorización imposible: A es singular o no admite factorización LU.")
            return None, None

        L[i, i] = 1  # La diagonal de L es 1 por definición

        # Paso 2 y Paso 5: Calcular elementos fuera de la diagonal
        for j in range(i + 1, n):
            # Elementos de la fila i de U
            sum_u = sum(L[i, k] * U[k, j] for k in range(i))
            U[i, j] = (A[i, j] - sum_u) / L[i, i]

            # Elementos de la columna i de L
            sum_l = sum(L[j, k] * U[k, i] for k in range(i))
            L[j, i] = (A[j, i] - sum_l) / U[i, i]

    return L, U

In [5]:
# Ejecución de la fución para resolver el ejemplo 2 de la página 301
A = np.array([[1, 1, 0, 3],
              [2, 1, -1, 1],
              [3, -1, -1, 2],
              [-1, 2, 3, -1]], dtype=float) #matriz A

L, U = fLU(A) # llamar a la función

if L is not None and U is not None:
    print("Matriz L:")
    print(L)
    print("\nMatriz U:")
    print(U)

    # Verificación: A = L * U
    print("\nVerificación A = L * U:")
    print(np.dot(L, U))

Matriz L:
[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]

Matriz U:
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]

Verificación A = L * U:
[[ 1.  1.  0.  3.]
 [ 2.  1. -1.  1.]
 [ 3. -1. -1.  2.]
 [-1.  2.  3. -1.]]
