<a href="https://colab.research.google.com/github/salmeronale/metodos-numericos/blob/main/Pivoteo_parcial_escalado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np

In [22]:
#definir la función del proceso de pivoteo parcial escalado
def ppe(A, b):

    n = len(A)
    A = A.astype(float)
    b = b.astype(float)

    #escalas para cada fila
    escala = np.max(np.abs(A), axis=1)

    print("matriz inicial:")
    print(A)
    print("vector independiente inicial:")
    print(b)

    #recorremos las columnas
    for k in range(n - 1):
        #selección del pivote escalado
        razones = np.abs(A[k:n, k]) / escala[k:n]
        max_index = np.argmax(razones) + k

        #intercambiamos filas si es necesario
        if max_index != k:
            A[[k, max_index]] = A[[max_index, k]]
            b[[k, max_index]] = b[[max_index, k]]
            escala[[k, max_index]] = escala[[max_index, k]]

        print(f"\nmatriz después del intercambio en la columna {k+1}:")
        print(A)
        print("vector independiente:")
        print(b)

        #proceso de eliminación gaussiana
        for i in range(k + 1, n):
            factor = A[i, k] / A[k, k]
            A[i, k:] -= factor * A[k, k:]
            b[i] -= factor * b[k]

        print(f"\nmatriz después de la eliminación en la columna {k+1}:")
        print(A)
        print("vector independiente:")
        print(b)

    #proceso de sustitución hacia atrás
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(A[i, i + 1:], x[i + 1:])) / A[i, i]

    print("\nmatriz triangular superior:")
    print(A)
    print("vector independiente final:")
    print(b)

    return x

In [23]:
#definir una función para solicitar los datos
def datos():

    n = int(input("ingrese el número de ecuaciones: "))
    m = n + 1

    print("ingrese los coeficientes de la matriz aumentada dejando solo un espacio en blanco como separación :")
    matriz_aumentada = []
    for i in range(n):
        fila = list(map(float, input(f"Fila {i + 1}: ").split()))
        if len(fila) != m:
            raise ValueError(f"cada fila debe tener exactamente {m} valores.")
        matriz_aumentada.append(fila)

    matriz_aumentada = np.array(matriz_aumentada)
    A = matriz_aumentada[:, :-1]
    b = matriz_aumentada[:, -1]

    return A, b

In [25]:
#emplear ambas funciones
try:
    A, b = datos()
    solucion = ppe(A, b)
    print("")
    print("la olución es:", solucion)
except Exception as e:
    print("Error:", e)

ingrese el número de ecuaciones: 3
ingrese los coeficientes de la matriz aumentada dejando solo un espacio en blanco como separación :
Fila 1: 2.11 -4.21 0.921 2.01
Fila 2: 4.01 10.2 -1.12 -3.09
Fila 3: 1.09 0.987 0.832 4.21
matriz inicial:
[[ 2.11  -4.21   0.921]
 [ 4.01  10.2   -1.12 ]
 [ 1.09   0.987  0.832]]
vector independiente inicial:
[ 2.01 -3.09  4.21]

matriz después del intercambio en la columna 1:
[[ 1.09   0.987  0.832]
 [ 4.01  10.2   -1.12 ]
 [ 2.11  -4.21   0.921]]
vector independiente:
[ 4.21 -3.09  2.01]

matriz después de la eliminación en la columna 1:
[[ 1.09        0.987       0.832     ]
 [ 0.          6.56892661 -4.18084404]
 [ 0.         -6.12061468 -0.68956881]]
vector independiente:
[  4.21       -18.57816514  -6.13963303]

matriz después del intercambio en la columna 2:
[[ 1.09        0.987       0.832     ]
 [ 0.         -6.12061468 -0.68956881]
 [ 0.          6.56892661 -4.18084404]]
vector independiente:
[  4.21        -6.13963303 -18.57816514]

matriz de